version: "3"

services:
  ingress:
    container_name: ingress
    build: ./ingress
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - pizza
    volumes:
      - ./static:/static
      - ./media:/media
    environment:
      DNS_HOST_NAME: "${DNS_HOST_NAME}"
  pizza:
    container_name: pizza
    build: .
    environment:
      SECRET_KEY: "${SECRET_KEY}"
      DB_NAME: "${DB_NAME}"
      PORT: "${PORT}"
      DB_USER: "${DB_USER}"
      DB_PORT: "${DB_PORT}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DNS_HOST_NAME: "${DNS_HOST_NAME}"
      DATABASE_URL: "${DATABASE_URL}"
    volumes:
      - ./static:/static
      - ./media:/media
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
volumes:
  static:
  media: