export DEBUG=True
export PORT=80
echo $PORT
export SECRET_KEY='django-insecure-&mw1navgnh8#fxxhad#33kf)yrj+pzy!pfs9^3)r6@h76+k-hf'
echo $SECRET_KEY
export DATABASE_URL='postgres://postgres:1234@localhost/pizza'
echo $DATABASE_URL
export DB_NAME="pizza"
echo $DB_NAME
export DB_USER="postgres"
echo $DB_USER
export DB_PORT="5432"
echo $DB_PORT
export DB_PASSWORD="1234"
echo $DB_PASSWORD
export DB_HOST="0.0.0.0"
echo $DB_HOST
export DNS_HOST_NAME="0.0.0.0"
echo $DNS_HOST_NAME
