# Generated by Django 4.2 on 2023-04-22 19:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='svg/', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='Logo')),
                ('desktop_image', models.ImageField(upload_to='images/', verbose_name='Desktop Image')),
                ('mobile_image', models.ImageField(upload_to='images/', verbose_name='Mobile Image')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Subtitle')),
                ('desc', models.TextField(verbose_name='Description')),
                ('delivery_text', models.CharField(max_length=255, verbose_name='Delivery text')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/products')),
                ('mobile_img', models.ImageField(upload_to='images/mobile/products')),
                ('name', models.CharField(max_length=55, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='svg/', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='Icon')),
                ('name', models.CharField(max_length=55, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Product component',
                'verbose_name_plural': 'Product components',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(verbose_name='Size')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_size_foreign', to='home.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_foreign', to='home.size')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='component',
            field=models.ManyToManyField(to='home.productcomponents'),
        ),
    ]
