# Generated by Django 4.2 on 2023-04-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
