  GNU nano 6.4                   /etc/nginx/sites-available/pizza.conf
server {
        listen 80;
        server_name grtak.am;

    location /static/ {
            autoindex on;
            alias /home/pizza/static/;
    }
    location /media/ {
            autoindex on;
            alias /home/pizza/media/;
    }

    location / {
            add_header Access-Control-Allow-Origin * always;
            add_header Access-Control-Allow-Headers * always;
            add_header Access-Control-Allow-Methods * always;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://grtak.am:8000;
    }
}