# Generated by Django 4.2 on 2023-07-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='server_host',
            field=models.CharField(default='smtp.sendgrid.net', max_length=100, verbose_name='Server Host'),
        ),
    ]
